@startuml

'¿eby odró¿niæ od klasy Uzytkownik
actor Klient

Klient --> PanelUzytkownika : otworzenie panelu logowania i rejestracji
alt rejestracja
	PanelUzytkownika --> PanelUzytkownika : pobranie danych od uzytkownika
	PanelUzytkownika --> PanelUzytkownika : weryfikacja danych
	PanelUzytkownika --> ObslugaPliku : zapisanie w pliku nowego uzytkownika
	PanelUzytkownika --> Menu : wyswietlenie Menu dostepnego dla Uzytkownika utworzonego na podstawie danych rejestracji
else uzytkownik juz istnieje
	PanelUzytkownika --> PanelUzytkownika : popros o inne dane lub zaproponuj zalogowanie sie
else bledne dane
	PanelUzytkownika --> PanelUzytkownika : popros o prawidlowe dane	
end

alt logowanie
	PanelUzytkownika --> Menu : wyswietlenie Menu dostepnego dla Uzytkownika po wprowadzeniu danych
else uzytkownik podal nieprawidlowe dane
	PanelUzytkownika --> PanelUzytkownika : popros uzytkownika o ponowne podanie danych
end

alt odpytanie
	Klient --> Odpytanie : otworzenie okna odpytania dla uzytkownika zapisanego w Menu
	ObslugaPliku --> Odpytanie : pobranie listy pytan i odpowiedzi z pliku
	loop
		Odpytanie --> Odpytanie : zadanie pytania i oczekiwanie na odpowiedz Uzytkownika
	end
	Odpytanie --> Odpytanie : wyswietlenie oceny
	Odpytanie --> ObslugaPliku : zapisanie wynikow do pliku
end

alt wyswietlenie ocen
	Klient --> WyswietlOceny : otworzenie okna wyswietlania ocen ucznia
	alt uzytkownik jest uczniem
		Menu --> Uzytkownik : wybranie uzytkownika jako ucznia do wyswietlenia oceny
	else uzytkownik nie jest uczniem
		Menu --> Uzytkownik : wyswietlenie listy uczniow do wyboru
		Uzytkownik --> Uzytkownik : wybranie ucznia do wyswietlenia oceny
	end
	ObslugaPliku --> WyswietlOceny : pobranie listy ocen z pliku
	Uzytkownik --> WyswietlOceny : wyswietlenie ocen ucznia
end

alt wyswietlenie slownikow
	Klient --> WyswietlPlik : otworzenie okna wyswietlania slownikow ucznia
	alt uzytkownik jest uczniem
		Menu --> Uzytkownik : wybranie uzytkownika jako ucznia do wyswietlenia slownikow
	else uzytkownik nie jest uczniem
		Menu --> Uzytkownik : wyswietlenie listy uczniow do wyboru
		Uzytkownik --> Uzytkownik : wybranie ucznia do wyswietlenia slownika
	end
	Uzytkownik --> WyswietlOceny : wyswietlenie listy slownikow
	Klient --> WyswietlPlik : uzytkownik wybiera slownik do wyswietlenia
	ObslugaPliku --> WyswietlPlik : pobranie listy pytan i odpowiedzi z pliku
	WyswietlPlik --> WyswietlPlik : wyswietlenie slownika uzytkownikowi
end

alt edytowanie slownikow
	Klient --> Edycja : otworzenie okna z lista plikow

end

@enduml