@startuml

class Main{
	public static void main();
}

class ObslugaPliku{
    private static int iloscStron = 0;
    private static double poprawneOdpowiedzi = 0.0;
    {field}private static final String sciezkaProgramu = new File("").getAbsolutePath(),
				sciezkaZestawSlowek = ObslugaPliku.sciezkaProgramu + "\\Slowniki",
				sciezkaOcen = ObslugaPliku.sciezkaProgramu + "\\Oceny";
    
    private static String nazwaPliku = "NowyPlikOdpytanie", 
			  rozszerzenie = ".txt",
			  nazwaPlikuOcen = "domyslne",
			  rozszerzenieOcen = ".txt",
			  pelnaNazwaPliku = sciezkaZestawSlowek + "\\" + nazwaPliku + rozszerzenie,
			  pelnaNazwaPlikuOcen = sciezkaOcen + "\\" + nazwaPlikuOcen + rozszerzenieOcen,
			  granicaSlow = ";";
    private static boolean czyMaZawartosc = false;
    {field}private static ArrayList<String> pytania = new ArrayList<>(),
			      {field}odpowiedzi = new ArrayList<>();
    {field}private static ArrayList<Ocena> oceny = new ArrayList<>();

    public static void ustawPlikUzytkownika(Uzytkownik uzytkownik);
    public static void setCzyMaZawartosc(boolean czyMaZawartosc);
    public static void setIloscStron();
    public static String czyPoprawnyString(String doSprawdzenia);
    public static boolean czyIstniejePlik(JFrame okno);
    public static void czyPlikMaZawartosc(String nazwaPliku);
    public static boolean czyPoprawnaZawartoscPliku(String linia);
    public static boolean czyPoprawnaZawartoscPlikuOcen(String linia);
    public static void przygotujFoldery();
    public static String czytanieZPliku(String nazwaPliku, boolean czyZapisac);
    public static String zapisDoPliku(Object[] pytania, Object[] odpowiedzi, boolean czyDopisac);
    public static String czytanieOcen(String nazwaPliku, boolean czyZapisac);
}

class Ocena{
	private String komunikat, nazwa;
    private int dolnaGranica, gornaGranica;

	public Ocena(String nazwa, int gornaGranica, int dolnaGranica, String komunikat);
    
    public String getKomunikat();
    
    public String getNazwa();
    
    public int getDolnaGranica();
    
    public int getGornaGranica();
    
    public String toString();
    
    public boolean czyWZakresie(int procent);
    
    public boolean czyWZakresie(double procent);
}

class PanelUzytkownika{
	public boolean Logowanie();
	public boolean Rejestracja();
	private boolean Weryfikacja(boolean czyLogowanie);
}

class Menu{
    {field}private ObslugaOkienka obslugaOkienka = new ObslugaOkienka();
    private ArrayList<JFrame> oknaOpcji;
    private Odpytanie oOdpytanie;
    private WyswietlPlik oWyswietlPlik;
    private Edycja oEdycja;
    private Uzytkownik uzytkownik;

    private void initComponents();
    public void myOptions();
    private void gOdpytanieActionPerformed(java.awt.event.ActionEvent evt);                            

    private void gOdczytActionPerformed(java.awt.event.ActionEvent evt);                                

    private void gZmianaPlikuActionPerformed(java.awt.event.ActionEvent evt);                                          

    private void gZapisActionPerformed(java.awt.event.ActionEvent evt);                                    

    public void zamknijWszystkieOkna();
    
    public void addOknaOpcji(JFrame okno);
}

class Edycja{
    private Uzytkownik uzytkownik;
    public void myOptions();
    public void wstawDane();
    public void zapiszDoTablicy(boolean czyTezDoPliku);
    public void usunZestaw(boolean czyZPliku);
    public void usunNa(int indeks);

}

class Odpytanie{
    private Uzytkownik uzytkownik;

    private void zadajPytanie();
    private void sprawdzOdpowiedz(String odpowiedz);
    private void ustawEtykietyOdpowiedzi(String eWerdykt, String eInfoOPoprawnej, String ePoprawnaOdpowiedz);
    public void pokazWynik(String nazwaPanelu);
}

class WyswietlPlik{
    private Uzytkownik uzytkownik;
}

class WyswietlOceny{
    private Uzytkownik uzytkownik;
}

abstract Uzytkownik{
    public final int RODZIC = 0,
                      UCZEN = 1,
                      NAUCZYCIEL = 2;
	public final String PESEL;
	public final String IMIE;
	public final String NAZWISKO;

    public abstract int getTypUzytkownika();
    public abstract Uczen wybierzUcznia();

}

class Uczen{
    public int getTypUzytkownika();
    public Uczen wybierzUcznia();
}

class Nauczyciel{
    public int getTypUzytkownika();
    public Uczen wybierzUcznia();
}

class Rodzic{
    public int getTypUzytkownika();
    public Uczen wybierzUcznia();
}


'-=-Relacje miêdzy obiektami-=-'

/'

--|> Dziedziczy po
--> Zawiera siê w
<o> Wywo³ywany w --  
"x" Posiada wiele --o "y" <iloœæ>
n Dowolna liczba


'/

 ObslugaPliku "o" -- Main
 ObslugaPliku "o" -- Menu
 ObslugaPliku "o" -- PanelUzytkownika

 Ocena "ObslugaPliku" --o "Ocena <n>" ObslugaPliku

 PanelUzytkownika "o" -- Main
 Menu "o" -- PanelUzytkownika

 Uzytkownik --> Menu
 Odpytanie --> Menu
 WyswietlPlik --> Menu
 WyswietlOceny --> Menu
 Edycja --> Menu

 Uzytkownik --> Odpytanie
 Uzytkownik --> WyswietlPlik
 Uzytkownik --> WyswietlOceny
 Uzytkownik --> Edycja

 Nauczyciel --|> Uzytkownik
 Uczen --|> Uzytkownik
 Rodzic --|> Uzytkownik

 Uczen "Rodzic" -up-o "Uczen <1-n>" Rodzic

 Uczen "Nauczyciel" -up-o "Uczen <1-n>" Nauczyciel

@enduml